export const siteConfig = {
  name: 'Sai Vishnu Vamsi Senagasetty',
  shortName: 'Sai Vishnu Vamsi',
  title: 'Sai Vishnu Vamsi Senagasetty | AI Developer · RAG & LLM Engineer',
  description:
    'AI Developer at Zibtek shipping production RAG chatbots, retrieval pipelines, and LLM product features. MS Computer Science — open to full-time AI Developer / AI Engineer roles.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://portfolio-updated.vercel.app',
  jobTitle: 'AI Developer / AI Engineer',
  location: 'Houston, Texas',
  email: 'saivishnuvamsis07@gmail.com',
  phone: '+1 346 901 8158',
  linkedin: 'https://www.linkedin.com/in/vishnu-senagasetty/',
  github: 'https://github.com/VishnuVamsi7',
  ogImage: '/og-image.png',
  keywords: [
    'AI Developer',
    'AI Engineer',
    'Machine Learning Engineer',
    'RAG',
    'LLM',
    'Chatbot',
    'FAISS',
    'FastAPI',
    'Zibtek',
    'TensorFlow',
    'PyTorch',
    'Groq',
    'Model Deployment',
    'NLP',
    'Houston',
  ],
};

export const sectionAnchors = [
  { id: 'about', label: 'About' },
  { id: 'skills', label: 'Skills' },
  { id: 'jd-match', label: 'JD Match' },
  { id: 'projects', label: 'Projects' },
  { id: 'experience', label: 'Experience' },
  { id: 'training', label: 'Training' },
  { id: 'badges', label: 'Badges' },
  { id: 'achievements', label: 'Achievements' },
  { id: 'contact', label: 'Contact' },
];
